#!/bin/bash -e

# based on https://github.com/cdown/travis-automerge/blob/master/travis-automerge by Chris Down
# modified from original to merge successful pull requests

# Define the following variables in the Travis environment
# $BRANCH_TO_MERGE_INTO
# $GITHUB_SECRET_TOKEN (mask this!)
# $GITHUB_REPO

export GIT_COMMITTER_EMAIL='travis@travis'
export GIT_COMMITTER_NAME='Travis CI'

# Since Travis does a partial checkout, we need to get the whole thing
repo_temp=$(mktemp -d)
git clone "https://github.com/$GITHUB_REPO" "$repo_temp"

cd "$repo_temp"

git branch -a 

printf 'Checking out %s\n' "$BRANCH_TO_MERGE_INTO" >&2
git checkout -b "$TRAVIS_PULL_REQUEST_BRANCH" origin/"$TRAVIS_PULL_REQUEST_BRANCH"
git checkout "$BRANCH_TO_MERGE_INTO"

git config --global user.email "$GIT_COMMITTER_EMAIL"
git config --global user.name "$GIT_COMMITTER_NAME"

printf 'Merging %s\n' "$TRAVIS_COMMIT" >&2
git merge --no-edit "$TRAVIS_PULL_REQUEST_BRANCH"

printf 'Pushing to %s\n' "$GITHUB_REPO" >&2

push_uri="https://$GITHUB_SECRET_TOKEN@github.com/$GITHUB_REPO"

# Redirect to /dev/null to avoid secret leakage
git push "$push_uri" "$BRANCH_TO_MERGE_INTO" >/dev/null 2>&1
